/**
 * server/utils/seed.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Database seeder for LeafyLoop.
 * Populates: Users (1 admin + 1 customer) + 12 Products
 *
 * Usage:  node utils/seed.js
 *         node utils/seed.js --wipe   (drops everything first)
 */

import mongoose from "mongoose";
import "dotenv/config";
import { Product } from "../models/Product.js";
import { User }    from "../models/User.js";
import { Order }   from "../models/Order.js";

const WIPE = process.argv.includes("--wipe");

// ─── Sample data ──────────────────────────────────────────────────────────────
const ADMIN = {
  name:         "Admin User",
  email:        "admin@leafyloop.in",
  password:     "Admin@1234",
  role:         "admin",
  authProvider: "local",
};

const CUSTOMER = {
  name:         "Priya Menon",
  email:        "priya@example.com",
  password:     "Priya@1234",
  role:         "user",
  authProvider: "local",
};

const PRODUCTS = [
  {
    name:             "Monstera Deliciosa",
    category:         "Indoor",
    description:      "The iconic Swiss cheese plant with stunning split leaves. Perfect for bright indoor spaces. Known for its air-purifying qualities and dramatic tropical aesthetic.",
    shortDescription: "Iconic split-leaf tropical plant for bright spaces",
    price:            799,
    compareAtPrice:   999,
    stock:            45,
    sku:              "LL-IN-001",
    height:           "60cm–1m",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    isFeatured:       true,
    tags:             ["tropical", "indoor", "air-purifier", "popular"],
    images: [
      { url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600", publicId: "seed_monstera_1", isPrimary: true, alt: "Monstera Deliciosa" },
    ],
  },
  {
    name:             "Snake Plant (Sansevieria)",
    category:         "Indoor",
    description:      "One of the most tolerant houseplants. Thrives in low light and irregular watering — perfect for beginners and busy plant parents. Excellent air purifier.",
    shortDescription: "Virtually indestructible, perfect for beginners",
    price:            449,
    compareAtPrice:   599,
    stock:            62,
    sku:              "LL-IN-002",
    height:           "30–60cm",
    sunlight:         "Low Light",
    water:            "Bi-Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    isFeatured:       true,
    tags:             ["beginner", "low-light", "air-purifier", "drought-tolerant"],
    images: [
      { url: "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=600", publicId: "seed_snake_1", isPrimary: true, alt: "Snake Plant" },
    ],
  },
  {
    name:             "Peace Lily",
    category:         "Indoor",
    description:      "Elegant white blooms year-round. One of the few flowering houseplants that thrives in low light. An excellent air purifier that removes benzene, formaldehyde, and carbon monoxide.",
    shortDescription: "Elegant bloomer that thrives in low light",
    price:            549,
    stock:            38,
    sku:              "LL-IN-003",
    height:           "30–60cm",
    sunlight:         "Low Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    isFeatured:       true,
    tags:             ["flowering", "low-light", "air-purifier", "beginner"],
    images: [
      { url: "https://images.unsplash.com/photo-1593482892540-b56c5a0b6148?w=600", publicId: "seed_peace_1", isPrimary: true, alt: "Peace Lily" },
    ],
  },
  {
    name:             "Pothos (Money Plant)",
    category:         "Indoor",
    description:      "The quintessential Indian houseplant. Trailing vines with heart-shaped leaves in golden and green. Extremely adaptable to various light conditions and drought tolerant.",
    shortDescription: "Classic trailing plant, perfect for hanging baskets",
    price:            249,
    stock:            88,
    sku:              "LL-IN-004",
    height:           "Upto 30cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    tags:             ["trailing", "money-plant", "beginner", "popular"],
    images: [
      { url: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?w=600", publicId: "seed_pothos_1", isPrimary: true, alt: "Pothos Money Plant" },
    ],
  },
  {
    name:             "ZZ Plant (Zamioculcas)",
    category:         "Indoor",
    description:      "Virtually indestructible with glossy dark green leaves. Thrives in neglect — perfect for offices and homes with low light. Drought-tolerant and long-lasting.",
    shortDescription: "Glossy leaves that thrive on neglect",
    price:            699,
    stock:            30,
    sku:              "LL-IN-005",
    height:           "30–60cm",
    sunlight:         "Low Light",
    water:            "Monthly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     false,
    tags:             ["low-light", "drought-tolerant", "office", "beginner"],
    images: [
      { url: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600", publicId: "seed_zz_1", isPrimary: true, alt: "ZZ Plant" },
    ],
  },
  {
    name:             "Spider Plant",
    category:         "Indoor",
    description:      "Classic air-purifying plant with long arching leaves and baby plantlets. Pet-friendly and extremely easy to care for. Great for hanging baskets.",
    shortDescription: "Pet-safe air purifier with charming baby plantlets",
    price:            329,
    stock:            55,
    sku:              "LL-IN-006",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      true,
    airPurifying:     true,
    isFeatured:       true,
    tags:             ["pet-friendly", "air-purifier", "hanging", "beginner"],
    images: [
      { url: "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=600", publicId: "seed_spider_1", isPrimary: true, alt: "Spider Plant" },
    ],
  },
  {
    name:             "Hibiscus (Chembarathi)",
    category:         "Outdoor",
    description:      "Kerala's beloved flower plant! Vibrant red blooms that attract butterflies and birds. Perfect for balconies and garden borders. Low maintenance once established.",
    shortDescription: "Kerala's beloved vibrant flowering shrub",
    price:            399,
    compareAtPrice:   499,
    stock:            40,
    sku:              "LL-OUT-001",
    height:           "1m–2m",
    sunlight:         "Full Sun",
    water:            "Daily",
    difficulty:       "Beginner",
    petFriendly:      true,
    isFeatured:       true,
    tags:             ["flowering", "kerala", "balcony", "butterfly-garden"],
    images: [
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600", publicId: "seed_hibiscus_1", isPrimary: true, alt: "Hibiscus Chembarathi" },
    ],
  },
  {
    name:             "Adenium (Desert Rose)",
    category:         "Outdoor",
    description:      "Stunning bonsai-like succulent with beautiful pink and red flowers. Perfect for Kerala's climate. Requires full sun and minimal watering. Long-lasting blooms.",
    shortDescription: "Stunning bonsai-like succulent with dramatic flowers",
    price:            1299,
    compareAtPrice:   1599,
    stock:            18,
    sku:              "LL-OUT-002",
    height:           "30–60cm",
    sunlight:         "Full Sun",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      false,
    isFeatured:       false,
    tags:             ["succulent", "bonsai", "flowering", "drought-tolerant"],
    images: [
      { url: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=600", publicId: "seed_adenium_1", isPrimary: true, alt: "Desert Rose Adenium" },
    ],
  },
  {
    name:             "Neem Tree Sapling",
    category:         "Outdoor",
    description:      "The legendary medicinal tree of India. Natural pest repellent, provides dense shade, and has numerous medicinal uses. Ideal for large gardens and compounds.",
    shortDescription: "Sacred medicinal tree with natural pest-repelling properties",
    price:            299,
    stock:            25,
    sku:              "LL-OUT-003",
    height:           "30–60cm",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      true,
    tags:             ["medicinal", "shade-tree", "traditional", "pest-repellent"],
    images: [
      { url: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600", publicId: "seed_neem_1", isPrimary: true, alt: "Neem Sapling" },
    ],
  },
  {
    name:             "Premium Organic Compost",
    category:         "Fertilizer",
    description:      "100% natural organic compost made from Kerala's finest agricultural waste. Enriched with vermicompost, neem cake, and bone meal. Ideal for all plants.",
    shortDescription: "100% natural fertilizer from Kerala's finest organic waste",
    price:            299,
    compareAtPrice:   399,
    stock:            120,
    sku:              "LL-FRT-001",
    fertilizerType:   "Organic",
    npkRatio:         "4-2-3",
    weightKg:         2,
    isFeatured:       true,
    tags:             ["organic", "compost", "all-purpose", "kerala"],
    images: [
      { url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600", publicId: "seed_compost_1", isPrimary: true, alt: "Organic Compost" },
    ],
  },
  {
    name:             "NPK 19-19-19 Water Soluble",
    category:         "Fertilizer",
    description:      "Balanced all-purpose fertilizer perfect for vegetable gardens and flowering plants. Fully water-soluble for easy application. Suitable for drip irrigation.",
    shortDescription: "Balanced NPK for lush growth in all garden types",
    price:            449,
    stock:            75,
    sku:              "LL-FRT-002",
    fertilizerType:   "Chemical",
    npkRatio:         "19-19-19",
    weightKg:         1,
    tags:             ["npk", "water-soluble", "vegetables", "flowers"],
    images: [
      { url: "https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?w=600", publicId: "seed_npk_1", isPrimary: true, alt: "NPK Fertilizer" },
    ],
  },
  {
    name:             "Terracotta Pot — 8 inch",
    category:         "Pots & Planters",
    description:      "Traditional Kerala-style handcrafted terracotta pot. Excellent drainage and breathability for healthy root systems. Aged finish that gets more beautiful over time.",
    shortDescription: "Handcrafted terracotta with natural breathability",
    price:            199,
    compareAtPrice:   249,
    stock:            200,
    sku:              "LL-POT-001",
    tags:             ["terracotta", "handcrafted", "drainage", "traditional"],
    images: [
      { url: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=600", publicId: "seed_pot_1", isPrimary: true, alt: "Terracotta Pot" },
    ],
  },
  // Additional Indoor Plants
  {
    name:             "Rubber Plant (Ficus)",
    category:         "Indoor",
    description:      "Bold statement plant with large glossy leaves that purify the air. Tolerates neglect and imperfect light conditions. Grows beautifully in any home.",
    shortDescription: "Bold leafy plant that adds drama to any space",
    price:            599,
    compareAtPrice:   749,
    stock:            32,
    sku:              "LL-IN-007",
    height:           "1m–2m",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    isFeatured:       true,
    tags:             ["bold", "air-purifier", "statement", "beginner"],
    images: [
      { url: "https://images.unsplash.com/photo-1568705686620-3f171b4d5f1b?w=600", publicId: "seed_rubber_1", isPrimary: true, alt: "Rubber Plant" },
    ],
  },
  {
    name:             "Boston Fern",
    category:         "Indoor",
    description:      "Feathery, delicate fronds create a lush tropical feeling. Excellent humidifier and air purifier. Prefers moist environment and indirect light.",
    shortDescription: "Lush tropical fern that increases humidity naturally",
    price:            449,
    stock:            28,
    sku:              "LL-IN-008",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Every 2–3 Days",
    difficulty:       "Intermediate",
    petFriendly:      true,
    airPurifying:     true,
    tags:             ["fern", "humidity-loving", "pet-friendly", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1625246333195-78d9c38ad576?w=600", publicId: "seed_fern_1", isPrimary: true, alt: "Boston Fern" },
    ],
  },
  {
    name:             "Areca Palm (Butterfly Palm)",
    category:         "Indoor",
    description:      "Graceful tropical palm with feathery yellow-green fronds. Creates tropical vibes indoors. Is one of the best air-purifying plants available.",
    shortDescription: "Tropical palm that brings island vibes inside",
    price:            899,
    compareAtPrice:   1099,
    stock:            20,
    sku:              "LL-IN-009",
    height:           "1m–2m",
    sunlight:         "Bright Indirect",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      true,
    airPurifying:     true,
    tags:             ["palm", "tropical", "air-purifier", "pet-friendly"],
    images: [
      { url: "https://images.unsplash.com/photo-1596204014174-9691d8ad8e5e?w=600", publicId: "seed_areca_1", isPrimary: true, alt: "Areca Palm" },
    ],
  },
  {
    name:             "Dracaena (Dragon Plant)",
    category:         "Indoor",
    description:      "Modern architectural plant with striking striped leaves in green and yellow. Extremely tolerant of neglect and low light. NASA air-purifier certified.",
    shortDescription: "Striped modern plant that thrives on neglect",
    price:            529,
    stock:            35,
    sku:              "LL-IN-010",
    height:           "60cm–1m",
    sunlight:         "Low Light",
    water:            "Bi-Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    tags:             ["modern", "low-light", "air-purifier", "beginner"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_dracaena_1", isPrimary: true, alt: "Dracaena Dragon Plant" },
    ],
  },
  {
    name:             "Philodendron (Heart Leaf)",
    category:         "Indoor",
    description:      "Heart-shaped leaves on trailing vines. Similar to Pothos but with larger leaves. Excellent for hanging baskets and wall shelves. Tolerates low light.",
    shortDescription: "Heart-shaped leaves on elegant trailing vines",
    price:            379,
    stock:            42,
    sku:              "LL-IN-011",
    height:           "30–60cm",
    sunlight:         "Low Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    airPurifying:     true,
    tags:             ["trailing", "heart-shaped", "low-light", "hanging"],
    images: [
      { url: "https://images.unsplash.com/photo-1605931323384-8d93aae24b6f?w=600", publicId: "seed_philodendron_1", isPrimary: true, alt: "Heart Leaf Philodendron" },
    ],
  },
  {
    name:             "Calathea (Prayer Plant)",
    category:         "Indoor",
    description:      "Stunning patterned leaves with pink undersides. Leaves fold up at night like praying hands (hence the name). Prefers humid environments, perfect for bathrooms.",
    shortDescription: "Patterned leaves that move with prayer-like motion",
    price:            649,
    stock:            18,
    sku:              "LL-IN-012",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      true,
    tags:             ["patterned", "prayer-plant", "humidity-loving", "unique"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848212624-ba5f36e6a695?w=600", publicId: "seed_calathea_1", isPrimary: true, alt: "Calathea Prayer Plant" },
    ],
  },
  {
    name:             "Jade Plant (Money Tree)",
    category:         "Indoor",
    description:      "Succulent with thick fleshy leaves and woody stem. Symbolizes prosperity and wealth in many cultures. Extremely low maintenance and long-living.",
    shortDescription: "Succulent money plant that symbolizes prosperity",
    price:            499,
    compareAtPrice:   649,
    stock:            38,
    sku:              "LL-IN-013",
    height:           "30–60cm",
    sunlight:         "Bright Indirect",
    water:            "Bi-Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["succulent", "money-tree", "prosperity", "long-living"],
    images: [
      { url: "https://images.unsplash.com/photo-1587654780221-a9838dc04fcf?w=600", publicId: "seed_jade_1", isPrimary: true, alt: "Jade Plant" },
    ],
  },
  {
    name:             "Anthurium (Flamingo Flower)",
    category:         "Indoor",
    description:      "Exotic waxy red heart-shaped blooms that last for weeks. Great for tropical interiors. Thrives in warm humidity and indirect light.",
    shortDescription: "Exotic heart-shaped red flowers that last weeks",
    price:            749,
    compareAtPrice:   999,
    stock:            22,
    sku:              "LL-IN-014",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      false,
    tags:             ["flowering", "exotic", "tropical", "long-blooming"],
    images: [
      { url: "https://images.unsplash.com/photo-1584849297244-87f4792b5f90?w=600", publicId: "seed_anthurium_1", isPrimary: true, alt: "Anthurium Flamingo Flower" },
    ],
  },
  // Additional Outdoor Plants
  {
    name:             "Croton (Codiaeum)",
    category:         "Outdoor",
    description:      "Multi-colored foliage with vibrant red, orange, and yellow leaves. Perfect for Kerala's tropical climate. Needs full sun to achieve brilliant colors.",
    shortDescription: "Rainbow-colored foliage for vibrant garden spaces",
    price:            429,
    stock:            30,
    sku:              "LL-OUT-004",
    height:           "60cm–1m",
    sunlight:         "Full Sun",
    water:            "Daily",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["colorful", "vibrant", "tropical", "full-sun"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848215624-ba5f36e6a695?w=600", publicId: "seed_croton_1", isPrimary: true, alt: "Croton" },
    ],
  },
  {
    name:             "Bougainvillea",
    category:         "Outdoor",
    description:      "Brilliant papery bracts in pink, red, or purple. Flowers all year in tropical climates. Perfect for trellises, fences, and pergolas.",
    shortDescription: "Vibrant papery flowers for stunning garden displays",
    price:            349,
    compareAtPrice:   449,
    stock:            45,
    sku:              "LL-OUT-005",
    height:           "2m+",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      false,
    isFeatured:       true,
    tags:             ["flowering", "vibrant", "climbing", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848213933-89c5cde1f0c1?w=600", publicId: "seed_bougainvillea_1", isPrimary: true, alt: "Bougainvillea" },
    ],
  },
  {
    name:             "Jasmine (Malli)",
    category:         "Outdoor",
    description:      "Kerala's fragrant treasure! Delicate white flowers with intoxicating evening fragrance. Perfect for home gardens and wedding decorations.",
    shortDescription: "Fragrant white flowers with divine evening scent",
    price:            299,
    stock:            50,
    sku:              "LL-OUT-006",
    height:           "1m–2m",
    sunlight:         "Indirect Light",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      true,
    isFeatured:       true,
    tags:             ["fragrant", "kerala", "malli", "flowering"],
    images: [
      { url: "https://images.unsplash.com/photo-1598225050826-26fda29b7c07?w=600", publicId: "seed_jasmine_1", isPrimary: true, alt: "Jasmine Malli" },
    ],
  },
  {
    name:             "Plumbago",
    category:         "Outdoor",
    description:      "Sky-blue or red flowers throughout the year. Hardy plant that tolerates heat and drought. Excellent for hedges and border plantings.",
    shortDescription: "Sky-blue flowers on hardy evergreen shrub",
    price:            279,
    stock:            35,
    sku:              "LL-OUT-007",
    height:           "1m–2m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      true,
    tags:             ["flowering", "blue", "hardy", "hedge"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_plumbago_1", isPrimary: true, alt: "Plumbago" },
    ],
  },
  {
    name:             "Mango Tree Sapling",
    category:         "Outdoor",
    description:      "The king of fruits! High-yield young mango tree ready for planting. Brings home fresh mangoes in 3-4 years. Thrives in Kerala's climate.",
    shortDescription: "Young mango tree bearing fruit in 3-4 years",
    price:            649,
    compareAtPrice:   799,
    stock:            15,
    sku:              "LL-OUT-008",
    height:           "60cm–1m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Intermediate",
    petFriendly:      true,
    isFeatured:       true,
    tags:             ["fruit-tree", "mango", "yielding", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810935-e4e83f2e6e4f?w=600", publicId: "seed_mango_1", isPrimary: true, alt: "Mango Sapling" },
    ],
  },
  {
    name:             "Coconut Palm",
    category:         "Outdoor",
    description:      "Iconic palm of Kerala! Provides coconuts and creates tropical shade. Strong and resilient in coastal areas. Requires space and patience.",
    shortDescription: "Iconic Kerala palm producing coconuts",
    price:            899,
    stock:            8,
    sku:              "LL-OUT-009",
    height:           "1m–2m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Intermediate",
    petFriendly:      true,
    tags:             ["palm", "coconut", "kerala", "shade-tree"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848212624-ba5f36e6a695?w=600", publicId: "seed_coconut_1", isPrimary: true, alt: "Coconut Palm" },
    ],
  },
  // Additional Fertilizers
  {
    name:             "Seaweed Extract Liquid Fertilizer",
    category:         "Fertilizer",
    description:      "Sea-derived liquid fertilizer rich in micronutrients and growth hormones. Boosts plant immunity and stress tolerance. Organic certified.",
    shortDescription: "Organic seaweed extract for superior plant health",
    price:            349,
    stock:            60,
    sku:              "LL-FRT-003",
    fertilizerType:   "Organic",
    tags:             ["liquid", "organic", "seaweed", "micronutrients"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_seaweed_1", isPrimary: true, alt: "Seaweed Extract" },
    ],
  },
  {
    name:             "Neem Oil Spray",
    category:         "Fertilizer",
    description:      "Natural pesticide from neem seeds. Controls fungal infections, mites, and insects without chemicals. Safe for organic gardening.",
    shortDescription: "Organic pest control from ancient neem tree",
    price:            199,
    stock:            85,
    sku:              "LL-FRT-004",
    fertilizerType:   "Organic",
    tags:             ["organic", "pesticide", "neem", "fungicide"],
    images: [
      { url: "https://images.unsplash.com/photo-1599598419255-d6f8fc1d3a0e?w=600", publicId: "seed_neemoil_1", isPrimary: true, alt: "Neem Oil" },
    ],
  },
  {
    name:             "Vermicompost (Worm Castings)",
    category:         "Fertilizer",
    description:      "Rich worm castings from earthworm composting. Improves soil structure and water retention. Full of beneficial microbes for healthy roots.",
    shortDescription: "Nutrient-rich worm castings for vibrant growth",
    price:            279,
    compareAtPrice:   349,
    stock:            95,
    sku:              "LL-FRT-005",
    fertilizerType:   "Organic",
    weightKg:         1,
    tags:             ["compost", "vermi", "organic", "microbes"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_vermi_1", isPrimary: true, alt: "Vermicompost" },
    ],
  },
  {
    name:             "Bone Meal (Phosphate)",
    category:         "Fertilizer",
    description:      "Natural phosphate-rich fertilizer for flower and fruit production. Promotes strong roots and excellent blooming. OMRI certified organic.",
    shortDescription: "Phosphate-rich for stunning blooms and fruiting",
    price:            249,
    stock:            70,
    sku:              "LL-FRT-006",
    fertilizerType:   "Organic",
    weightKg:         1,
    tags:             ["organic", "phosphate", "flowering", "fruiting"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_bone_1", isPrimary: true, alt: "Bone Meal" },
    ],
  },
  // Additional Pots & Planters
  {
    name:             "Ceramic Planter — 10 inch",
    category:         "Pots & Planters",
    description:      "Modern ceramic planter with drainage hole. Available in white, grey, and black. Durable and complements any home decor style.",
    shortDescription: "Modern ceramic pot in multiple contemporary colors",
    price:            349,
    compareAtPrice:   449,
    stock:            80,
    sku:              "LL-POT-002",
    tags:             ["ceramic", "modern", "white", "drainage"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_ceramic_1", isPrimary: true, alt: "Ceramic Planter" },
    ],
  },
  {
    name:             "Hanging Basket with Chain",
    category:         "Pots & Planters",
    description:      "Coir and plastic hanging basket perfect for trailing plants. Comes with sturdy chain. Ideal for balconies and patios.",
    shortDescription: "Hanging basket perfect for trailing plants",
    price:            179,
    stock:            120,
    sku:              "LL-POT-003",
    tags:             ["hanging", "basket", "trailing", "balcony"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_hanging_1", isPrimary: true, alt: "Hanging Basket" },
    ],
  },
  {
    name:             "Plastic Nursery Pot — 6 inch",
    category:         "Pots & Planters",
    description:      "Sturdy plastic pot perfect for young plants and propagation. Multiple drainage holes ensure excellent root aeration.",
    shortDescription: "Affordable plastic pot for plant propagation",
    price:            49,
    stock:            300,
    sku:              "LL-POT-004",
    tags:             ["plastic", "nursery", "drainage", "affordable"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_nursery_1", isPrimary: true, alt: "Nursery Pot" },
    ],
  },
  {
    name:             "Decorative Plant Stand",
    category:         "Pots & Planters",
    description:      "Wooden plant stand with 3 tiers. Perfect for displaying multiple plants beautifully. Adds vintage aesthetic to any corner.",
    shortDescription: "Wooden stand for displaying plants beautifully",
    price:            1299,
    compareAtPrice:   1799,
    stock:            12,
    sku:              "LL-POT-005",
    tags:             ["stand", "wooden", "display", "vintage"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_stand_1", isPrimary: true, alt: "Plant Stand" },
    ],
  },
  // Seeds
  {
    name:             "Tomato Seeds (Hybrid F1)",
    category:         "Seeds",
    description:      "High-yielding hybrid tomato seeds. Disease resistant and perfect for Kerala climate. Ready to fruit in 60-70 days.",
    shortDescription: "High-yield hybrid seeds ready in 60-70 days",
    price:            99,
    stock:            150,
    sku:              "LL-SEED-001",
    tags:             ["vegetable", "tomato", "hybrid", "fast-growing"],
    images: [
      { url: "https://images.unsplash.com/photo-1585761269610-c7722b88c987?w=600", publicId: "seed_tomato_1", isPrimary: true, alt: "Tomato Seeds" },
    ],
  },
  {
    name:             "Basil Seeds (Green Wonder)",
    category:         "Seeds",
    description:      "Aromatic basil perfect for cooking and tea. Grows quickly and produces leaves continuously. Prefers warm weather.",
    shortDescription: "Aromatic culinary basil seeds for fresh herbs",
    price:            79,
    stock:            200,
    sku:              "LL-SEED-002",
    tags:             ["herb", "culinary", "basil", "aromatic"],
    images: [
      { url: "https://images.unsplash.com/photo-1569070622148-e71588878470?w=600", publicId: "seed_basil_1", isPrimary: true, alt: "Basil Seeds" },
    ],
  },
  {
    name:             "Sunflower Seeds",
    category:         "Seeds",
    description:      "Tall sunflowers with large golden blooms. Perfect for children's gardens. Edible seeds after flowering and drying.",
    shortDescription: "Giant yellow flowers that brighten any garden",
    price:            89,
    stock:            180,
    sku:              "LL-SEED-003",
    tags:             ["flower", "sunflower", "tall", "edible-seeds"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848215624-ba5f36e6a695?w=600", publicId: "seed_sunflower_1", isPrimary: true, alt: "Sunflower Seeds" },
    ],
  },
  // Tools
  {
    name:             "Garden Tool Set (5-piece)",
    category:         "Tools",
    description:      "Essential gardening tools: spade, fork, hoe, cultivator, and trowel. Rust-resistant steel with comfortable wooden handles.",
    shortDescription: "5 essential tools for complete garden maintenance",
    price:            799,
    compareAtPrice:   999,
    stock:            40,
    sku:              "LL-TOOL-001",
    tags:             ["tools", "set", "gardening", "essential"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_toolset_1", isPrimary: true, alt: "Garden Tool Set" },
    ],
  },
  {
    name:             "Pruning Shears (Bypass)",
    category:         "Tools",
    description:      "Sharp stainless steel pruning shears for precise cuts. Ergonomic handles reduce hand fatigue. Perfect for trimming and deadheading.",
    shortDescription: "Sharp bypass shears for precise plant trimming",
    price:            349,
    stock:            75,
    sku:              "LL-TOOL-002",
    tags:             ["pruning", "shears", "trimming", "bypass"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_pruning_1", isPrimary: true, alt: "Pruning Shears" },
    ],
  },
  {
    name:             "Watering Can (2L Capacity)",
    category:         "Tools",
    description:      "Plastic watering can with removable shower head. Perfect amount for indoor and small outdoor plants. Lightweight and durable.",
    shortDescription: "2-liter watering can with adjustable shower head",
    price:            149,
    stock:            100,
    sku:              "LL-TOOL-003",
    tags:             ["watering", "can", "indoor", "lightweight"],
    images: [
      { url: "https://images.unsplash.com/photo-1599099075183-bc2a0d38ba5d?w=600", publicId: "seed_watering_1", isPrimary: true, alt: "Watering Can" },
    ],
  },
  {
    name:             "Gardening Gloves (Nitrile)",
    category:         "Tools",
    description:      "Durable nitrile gloves with grip pattern. Protects hands while weeding and planting. Washable and long-lasting.",
    shortDescription: "Protective gloves with excellent grip",
    price:            99,
    stock:            150,
    sku:              "LL-TOOL-004",
    tags:             ["gloves", "protection", "nitrile", "grip"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_gloves_1", isPrimary: true, alt: "Gardening Gloves" },
    ],
  },
  // More Premium Indoor Plants
  {
    name:             "Monstera Deliciosa Variegata",
    category:         "Indoor",
    description:      "Rare variegated monstera with white patches on split leaves. Ultra-premium plant for collectors. Thrives in bright indirect light.",
    shortDescription: "Exclusive variegated monstera for collectors",
    price:            2499,
    compareAtPrice:   3299,
    stock:            8,
    sku:              "LL-IN-015",
    height:           "1m–2m",
    sunlight:         "Bright Indirect",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      false,
    isFeatured:       true,
    tags:             ["rare", "variegated", "collector", "premium"],
    images: [
      { url: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600", publicId: "seed_monstera_var_1", isPrimary: true, alt: "Variegated Monstera" },
    ],
  },
  {
    name:             "Fiddle Leaf Fig (Ficus Lyrata)",
    category:         "Indoor",
    description:      "Statement plant with large violin-shaped leaves. Dramatic focal point for modern interiors. Requires bright light and patience.",
    shortDescription: "Dramatic violin-shaped statement plant",
    price:            1199,
    stock:            12,
    sku:              "LL-IN-016",
    height:           "1m–2m",
    sunlight:         "Bright Indirect",
    water:            "Weekly",
    difficulty:       "Intermediate",
    petFriendly:      false,
    tags:             ["statement", "modern", "bold", "large-leaf"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_fiddle_1", isPrimary: true, alt: "Fiddle Leaf Fig" },
    ],
  },
  {
    name:             "String of Pearls",
    category:         "Indoor",
    description:      "Succulent with delicate pearl-like beads on trailing strings. Perfect for hanging planters. Low maintenance and drought-tolerant.",
    shortDescription: "Unique pearl-like trailing succulent",
    price:            449,
    stock:            35,
    sku:              "LL-IN-017",
    height:           "30–60cm",
    sunlight:         "Bright Indirect",
    water:            "Bi-Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["succulent", "trailing", "unique", "hanging"],
    images: [
      { url: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600", publicId: "seed_pearls_1", isPrimary: true, alt: "String of Pearls" },
    ],
  },
  {
    name:             "Begonia (Rex)",
    category:         "Indoor",
    description:      "Stunning foliage plant with metallic leaves in silver, burgundy, and pink. Thrives in humid environments. Beautiful but requires attention.",
    shortDescription: "Metallic-leafed tropical beauty",
    price:            549,
    stock:            20,
    sku:              "LL-IN-018",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Expert",
    petFriendly:      false,
    tags:             ["foliage", "metallic", "tropical", "humidity"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848215624-ba5f36e6a695?w=600", publicId: "seed_begonia_1", isPrimary: true, alt: "Rex Begonia" },
    ],
  },
  {
    name:             "Syngonium (Pink Splash)",
    category:         "Indoor",
    description:      "Vibrant pink and white arrow-shaped leaves. Modern tropical look. Tolerates lower light and humidity variations.",
    shortDescription: "Pink-splashed tropical climber",
    price:            379,
    stock:            28,
    sku:              "LL-IN-019",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["pink", "modern", "tropical", "climbing"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_syngonium_1", isPrimary: true, alt: "Syngonium Pink" },
    ],
  },
  {
    name:             "Scindapsus Pictus (Satin Pothos)",
    category:         "Indoor",
    description:      "Heart-shaped leaves with silver spots on dark green foliage. Glossy satin-like appearance. Tolerates low light surprisingly well.",
    shortDescription: "Silvery-spotted tropical vine",
    price:            449,
    stock:            32,
    sku:              "LL-IN-020",
    height:           "30–60cm",
    sunlight:         "Low Light",
    water:            "Weekly",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["spotted", "trailing", "glossy", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1597848212624-ba5f36e6a695?w=600", publicId: "seed_satin_1", isPrimary: true, alt: "Satin Pothos" },
    ],
  },
  // More Outdoor Plants & Trees
  {
    name:             "Papaya Tree Sapling",
    category:         "Outdoor",
    description:      "Sweet, juicy papaya fruits in just 6-8 months! Fast-growing and perfect for Kerala's climate. Brings tropical abundance to backyard.",
    shortDescription: "Quick-fruiting papaya sapling",
    price:            199,
    stock:            40,
    sku:              "LL-OUT-010",
    height:           "30–60cm",
    sunlight:         "Full Sun",
    water:            "Daily",
    difficulty:       "Beginner",
    petFriendly:      true,
    tags:             ["fruit-tree", "papaya", "fast-growing", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810935-e4e83f2e6e4f?w=600", publicId: "seed_papaya_1", isPrimary: true, alt: "Papaya Sapling" },
    ],
  },
  {
    name:             "Banana Plant",
    category:         "Outdoor",
    description:      "Self-ripening bananas in 6 months! Requires space but very rewarding. Thrives in warm tropical climate like Kerala.",
    shortDescription: "Fruiting banana plant for Kerala",
    price:            299,
    stock:            25,
    sku:              "LL-OUT-011",
    height:           "1m–2m",
    sunlight:         "Full Sun",
    water:            "Daily",
    difficulty:       "Beginner",
    petFriendly:      false,
    tags:             ["fruit", "banana", "tropical", "fast-fruit"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_banana_1", isPrimary: true, alt: "Banana Plant" },
    ],
  },
  {
    name:             "Guava Tree Sapling",
    category:         "Outdoor",
    description:      "Hardy guava tree producing sweet juicy fruits. Disease-resistant and prolific fruiter. Ideal for large gardens.",
    shortDescription: "Prolific guava tree for large spaces",
    price:            349,
    stock:            20,
    sku:              "LL-OUT-012",
    height:           "60cm–1m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      true,
    tags:             ["fruit-tree", "guava", "hardy", "prolific"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_guava_1", isPrimary: true, alt: "Guava Sapling" },
    ],
  },
  {
    name:             "Pomegranate Tree",
    category:         "Outdoor",
    description:      "Beautiful flowering tree with red pomegranates. Ornamental and fruit-bearing. Perfect for Kerala's climate.",
    shortDescription: "Ornamental fruit tree with red pomegranates",
    price:            449,
    stock:            15,
    sku:              "LL-OUT-013",
    height:           "60cm–1m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Beginner",
    petFriendly:      true,
    isFeatured:       true,
    tags:             ["fruit-tree", "pomegranate", "ornamental", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_pomegranate_1", isPrimary: true, alt: "Pomegranate" },
    ],
  },
  {
    name:             "Rose Bush (Red)",
    category:         "Outdoor",
    description:      "Classic red roses with fragrant long-lasting blooms. Perfect for gardens and cut flowers. Requires regular pruning.",
    shortDescription: "Classic fragrant roses for gardens",
    price:            349,
    stock:            30,
    sku:              "LL-OUT-014",
    height:           "1m–2m",
    sunlight:         "Full Sun",
    water:            "Every 2–3 Days",
    difficulty:       "Intermediate",
    petFriendly:      false,
    tags:             ["flowering", "roses", "fragrant", "cutting"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_rose_1", isPrimary: true, alt: "Red Rose Bush" },
    ],
  },
  {
    name:             "Orchid (Dendrobium)",
    category:         "Outdoor",
    description:      "Exotic orchid with long-lasting flowers in multiple colors. Perfect for covered patios. Blocks or substrate planting.",
    shortDescription: "Exotic blooming orchid for patios",
    price:            799,
    compareAtPrice:   999,
    stock:            15,
    sku:              "LL-OUT-015",
    height:           "30–60cm",
    sunlight:         "Indirect Light",
    water:            "Every 2–3 Days",
    difficulty:       "Expert",
    petFriendly:      false,
    tags:             ["orchid", "exotic", "flowering", "tropical"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_orchid_1", isPrimary: true, alt: "Dendrobium Orchid" },
    ],
  },
  // More Fertilizers & Soil Products
  {
    name:             "Potting Mix (Premium Blend)",
    category:         "Fertilizer",
    description:      "Professional-grade potting mix with activated charcoal, perlite, and coco peat. Ensures perfect drainage and aeration.",
    shortDescription: "Premium potting mix for all houseplants",
    price:            249,
    compareAtPrice:   329,
    stock:            110,
    sku:              "LL-FRT-007",
    weightKg:         2,
    tags:             ["potting", "mix", "professional", "drainage"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_mix_1", isPrimary: true, alt: "Potting Mix" },
    ],
  },
  {
    name:             "Coconut Coir (Fiber)",
    category:         "Fertilizer",
    description:      "Sustainable coconut husk fiber as soil amendment. Improves water retention and aeration. Eco-friendly alternative to peat.",
    shortDescription: "Eco-friendly fiber for soil improvement",
    price:            179,
    stock:            90,
    sku:              "LL-FRT-008",
    weightKg:         1,
    tags:             ["coir", "eco-friendly", "sustainable", "soil"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_coir_1", isPrimary: true, alt: "Coconut Coir" },
    ],
  },
  {
    name:             "Perlite (Horticultural)",
    category:         "Fertilizer",
    description:      "Expanded volcanic glass for amazing drainage. Lightens heavy soil and prevents compaction. Essential for succulents.",
    shortDescription: "Volcanic glass for superior drainage",
    price:            149,
    stock:            85,
    sku:              "LL-FRT-009",
    weightKg:         1,
    tags:             ["perlite", "drainage", "succulent", "aeration"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_perlite_1", isPrimary: true, alt: "Perlite" },
    ],
  },
  {
    name:             "Epsom Salt (Magnesium)",
    category:         "Fertilizer",
    description:      "Natural magnesium sulfate to boost plant growth. Improves nutrient uptake and flowering. Safe and chemical-free.",
    shortDescription: "Natural magnesium for green growth",
    price:            129,
    stock:            100,
    sku:              "LL-FRT-010",
    weightKg:         0.5,
    tags:             ["magnesium", "epsom", "natural", "growth"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_epsom_1", isPrimary: true, alt: "Epsom Salt" },
    ],
  },
  {
    name:             "Activated Charcoal",
    category:         "Fertilizer",
    description:      "Prevents root rot and maintains soil health. Filters water in terrariums. Essential for plants prone to moisture issues.",
    shortDescription: "Charcoal for healthy roots and drainage",
    price:            159,
    stock:            70,
    sku:              "LL-FRT-011",
    weightKg:         0.5,
    tags:             ["charcoal", "drainage", "terrarium", "roots"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_charcoal_1", isPrimary: true, alt: "Charcoal" },
    ],
  },
  // More Pots & Planters
  {
    name:             "Terracotta Pot — 12 inch",
    category:         "Pots & Planters",
    description:      "Larger traditional terracotta pot for bigger plants. Excellent drainage and natural aging. Perfect for floor placement.",
    shortDescription: "Large handcrafted terracotta pot",
    price:            299,
    compareAtPrice:   349,
    stock:            80,
    sku:              "LL-POT-006",
    tags:             ["terracotta", "large", "traditional", "drainage"],
    images: [
      { url: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=600", publicId: "seed_pot_large_1", isPrimary: true, alt: "Large Terracotta Pot" },
    ],
  },
  {
    name:             "Concrete Planter (Grey)",
    category:         "Pots & Planters",
    description:      "Modern minimalist concrete planter. Heavy and durable for outdoors. Contemporary aesthetic for modern homes.",
    shortDescription: "Minimalist concrete planter",
    price:            499,
    stock:            25,
    sku:              "LL-POT-007",
    tags:             ["concrete", "modern", "minimalist", "outdoor"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_concrete_1", isPrimary: true, alt: "Concrete Planter" },
    ],
  },
  {
    name:             "Plastic Decorative Vase",
    category:         "Pots & Planters",
    description:      "Lightweight plastic decorative vase with glossy finish. Available in multiple colors. Affordable for outdoor placement.",
    shortDescription: "Colorful plastic decorative vase",
    price:            89,
    stock:            150,
    sku:              "LL-POT-008",
    tags:             ["plastic", "colorful", "lightweight", "decorative"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_vase_1", isPrimary: true, alt: "Plastic Vase" },
    ],
  },
  {
    name:             "Marble Planter Box",
    category:         "Pots & Planters",
    description:      "Elegant marble planter for premium indoor setups. Drains well and complements modern homes. Available in white and black.",
    shortDescription: "Elegant marble planter",
    price:            1699,
    compareAtPrice:   2199,
    stock:            8,
    sku:              "LL-POT-009",
    tags:             ["marble", "elegant", "premium", "modern"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_marble_1", isPrimary: true, alt: "Marble Planter" },
    ],
  },
  {
    name:             "Wall Mounted Planter",
    category:         "Pots & Planters",
    description:      "Space-saving wall-mounted planter perfect for small spaces. Creates vertical gardens beautifully. Includes wall mounts.",
    shortDescription: "Wall-mounted planter for vertical gardens",
    price:            249,
    stock:            60,
    sku:              "LL-POT-010",
    tags:             ["wall-mounted", "vertical", "space-saving", "modern"],
    images: [
      { url: "https://images.unsplash.com/photo-1599599810694-b308ca884533?w=600", publicId: "seed_wall_mount_1", isPrimary: true, alt: "Wall Planter" },
    ],
  },
  // More Seeds
  {
    name:             "Chili Pepper Seeds",
    category:         "Seeds",
    description:      "Spicy chili peppers ready to fruit in 75-90 days. Heat-loving plant perfect for Kerala's climate. Multiple harvest.",
    shortDescription: "Spicy chili seeds for fiery harvests",
    price:            69,
    stock:            120,
    sku:              "LL-SEED-004",
    tags:             ["vegetable", "chili", "pepper", "spicy"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_chili_1", isPrimary: true, alt: "Chili Seeds" },
    ],
  },
  {
    name:             "Coriander Seeds",
    category:         "Seeds",
    description:      "Fragrant coriander for fresh leaves and seeds. Fast-growing herb. Ready to harvest in 45 days.",
    shortDescription: "Aromatic coriander for cooking",
    price:            59,
    stock:            180,
    sku:              "LL-SEED-005",
    tags:             ["herb", "coriander", "aromatic", "fast-growing"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_coriander_1", isPrimary: true, alt: "Coriander Seeds" },
    ],
  },
  {
    name:             "Mint Seeds",
    category:         "Seeds",
    description:      "Refreshing mint perfect for tea and cooking. Grows aggressively (plant in containers!). Perennial harvest.",
    shortDescription: "Fresh mint for tea and cooking",
    price:            49,
    stock:            200,
    sku:              "LL-SEED-006",
    tags:             ["herb", "mint", "perennial", "refreshing"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_mint_1", isPrimary: true, alt: "Mint Seeds" },
    ],
  },
  {
    name:             "Marigold Seeds",
    category:         "Seeds",
    description:      "Bright cheerful marigolds for gardens and rangoli. Easy to grow and prolific bloomer. Natural pest repellent.",
    shortDescription: "Bright marigolds for festive gardens",
    price:            39,
    stock:            250,
    sku:              "LL-SEED-007",
    tags:             ["flower", "marigold", "easy", "pest-repellent"],
    images: [
      { url: "https://images.unsplash.com/photo-1599098075183-bc2a0d38ba5d?w=600", publicId: "seed_marigold_1", isPrimary: true, alt: "Marigold Seeds" },
    ],
  },
  // More Tools
  {
    name:             "Pruning Saw (Folding)",
    category:         "Tools",
    description:      "Compact folding pruning saw for cutting thick branches. Stainless steel blade and wooden handle. Fits in pocket.",
    shortDescription: "Compact folding saw for thick branches",
    price:            449,
    stock:            30,
    sku:              "LL-TOOL-005",
    tags:             ["saw", "pruning", "compact", "folding"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_saw_1", isPrimary: true, alt: "Pruning Saw" },
    ],
  },
  {
    name:             "Garden Hose (50ft)",
    category:         "Tools",
    description:      "Flexible durable garden hose with adjustable spray nozzle. Ideal for large gardens. Kink-resistant design.",
    shortDescription: "50ft flexible garden hose with nozzle",
    price:            649,
    compareAtPrice:   799,
    stock:            25,
    sku:              "LL-TOOL-006",
    tags:             ["hose", "watering", "large-garden", "durable"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_hose_1", isPrimary: true, alt: "Garden Hose" },
    ],
  },
  {
    name:             "Kneeling Bench",
    category:         "Tools",
    description:      "Ergonomic kneeling bench for easy garden work. Reduces strain on knees and back. Handles for support.",
    shortDescription: "Comfortable kneeling bench for gardening",
    price:            349,
    stock:            20,
    sku:              "LL-TOOL-007",
    tags:             ["kneeling", "ergonomic", "support", "comfort"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_bench_1", isPrimary: true, alt: "Kneeling Bench" },
    ],
  },
  {
    name:             "Soil Moisture Meter",
    category:         "Tools",
    description:      "Digital meter to measure soil moisture and pH. Never overwater again. Essential for plant parents.",
    shortDescription: "Digital moisture meter for perfect watering",
    price:            199,
    stock:            50,
    sku:              "LL-TOOL-008",
    tags:             ["meter", "digital", "moisture", "tech"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_meter_1", isPrimary: true, alt: "Moisture Meter" },
    ],
  },
  {
    name:             "Fertilizer Spreader",
    category:         "Tools",
    description:      "Handheld spreader for even fertilizer application. Saves time and ensures uniform distribution. Perfect for large areas.",
    shortDescription: "Handheld spreader for even fertilizing",
    price:            299,
    stock:            35,
    sku:              "LL-TOOL-009",
    tags:             ["spreader", "fertilizer", "handheld", "efficient"],
    images: [
      { url: "https://images.unsplash.com/photo-1589939705066-5470eb3d4e47?w=600", publicId: "seed_spreader_1", isPrimary: true, alt: "Spreader" },
    ],
  },
];

// ─── Seeder ───────────────────────────────────────────────────────────────────
async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB Atlas");

    if (WIPE) {
      await Promise.all([User.deleteMany(), Product.deleteMany(), Order.deleteMany()]);
      console.log("🗑  Wiped existing data");
    }

    // ── Users ──────────────────────────────────────────────────────────────
    const [adminExists, customerExists] = await Promise.all([
      User.findOne({ email: ADMIN.email }),
      User.findOne({ email: CUSTOMER.email }),
    ]);

    const admin    = adminExists    || await User.create(ADMIN);
    const customer = customerExists || await User.create(CUSTOMER);

    console.log(`👤 Admin:    ${admin.email}`);
    console.log(`👤 Customer: ${customer.email}`);

    // ── Products ───────────────────────────────────────────────────────────
    let created = 0;
    for (const p of PRODUCTS) {
      const exists = await Product.findOne({ sku: p.sku });
      if (!exists) {
        await Product.create(p);
        created++;
      }
    }
    console.log(`🌿 Products: ${created} created, ${PRODUCTS.length - created} already existed`);

    console.log("\n✨ Seed complete! LeafyLoop database is ready.\n");
    console.log("─── Login Credentials ────────────────────────────────");
    console.log(`Admin     │ ${ADMIN.email}    │ ${ADMIN.password}`);
    console.log(`Customer  │ ${CUSTOMER.email} │ ${CUSTOMER.password}`);
    console.log("──────────────────────────────────────────────────────\n");

  } catch (err) {
    console.error("❌ Seed failed:", err);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
}

seed();
